# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -timeout 15m -v ./...
      
    - name: Race
      run: go test -race ./core/...

    - name: Docker Push
      run: |
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker build . -t gochain/gochain:${GITHUB_REF_NAME}
        docker push gochain/gochain:${GITHUB_REF_NAME}
        echo $GOOGLE_AUTH > ${GITHUB_WORKSPACE}/gcloud-service-key.json
        echo $GOOGLE_AUTH | docker login -u _json_key --password-stdin https://gcr.io
        ./tmp/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${GITHUB_WORKSPACE}/gcloud-service-key.json
        docker tag gochain/gochain:${GITHUB_REF_NAME} gcr.io/gochain-core/gochain:${GITHUB_REF_NAME}
        docker push gcr.io/gochain-core/gochain:${GITHUB_REF_NAME}
